// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeP2yfZ9PHUjEP-kyhFUNKNSsygDCTfZE',
    appId: '1:663342835700:web:9fde84d3448f568c9e7ba1',
    messagingSenderId: '663342835700',
    projectId: 'ecommerce-5ff79',
    authDomain: 'ecommerce-5ff79.firebaseapp.com',
    storageBucket: 'ecommerce-5ff79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZNN5zUKiBl01Ih4HXxzYpJPzOfDAbnE',
    appId: '1:663342835700:android:8286979a0b73b0e29e7ba1',
    messagingSenderId: '663342835700',
    projectId: 'ecommerce-5ff79',
    storageBucket: 'ecommerce-5ff79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNgApEa09z47hmzp_cupMnQ-T0fp1MSUI',
    appId: '1:663342835700:ios:e8a598bcb3c92dcf9e7ba1',
    messagingSenderId: '663342835700',
    projectId: 'ecommerce-5ff79',
    storageBucket: 'ecommerce-5ff79.appspot.com',
    iosBundleId: 'com.example.trainFlutter',
  );
}
